/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107429-g90810bb37c-20220718"
#endif /* AVUTIL_FFVERSION_H */
